package com.xyan.frame.message.model;

import com.xyan.frame.base.model.BaseModel;

/**
 *@Description:   实体类 
 *				xy_message
 *@Author：wangming
 *@Date:2016-04-28 10:07:41
 */
public class MessageModel extends BaseModel{

	
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.ID.
	 *主键
	 */
	private Long id;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.FROM.
	 *发自
	 */
	private Long from;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.TO.
	 *目标，公共发言为-1
	 */
	private Long to;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.TITLE.
	 *标题
	 */
	private String title;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.CONTENT.
	 *内容
	 */
	private String content;
		
		public void setId(Long id){
		this.id=id;
	}
	
	public Long getId(){
		return this.id;
	}
		public void setFrom(Long from){
		this.from=from;
	}
	
	public Long getFrom(){
		return this.from;
	}
		public void setTo(Long to){
		this.to=to;
	}
	
	public Long getTo(){
		return this.to;
	}
		public void setTitle(String title){
		this.title=title;
	}
	
	public String getTitle(){
		return this.title;
	}
		public void setContent(String content){
		this.content=content;
	}
	
	public String getContent(){
		return this.content;
	}
		
}